version: '3'
services:
    mysql:
      image: ${MYSQL_IMAGE_BASE}:${MYSQL_IMAGE_TAG}
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      hostname: mysql
      ports:
        - "${MYSQL_HOST_PORT}:3306"
      volumes:
        - ${MYSQL_DATA_DIR}:/var/lib/mysql
        - ${MYSQL_CONF_FILE}:/etc/mysql/my.cnf
      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          TZ: $TZ
      networks:
        - backend
      restart: always
      container_name: ${MYSQL_CONTAINER_NAME}

    redis:
      image: redis:${REDIS_IMAGE_TAG}
      hostname: redis
      ports:
        - "${REDIS_HOST_PORT}:6379"
      command: redis-server /usr/local/etc/redis/redis.conf
      networks:
        - backend
      volumes:
        - ${REDIS_CONF_FILE}:/usr/local/etc/redis/redis.conf
        - ${REDIS_DATA_DIR}:/data
      environment:
        TZ: $TZ
      restart: always
      container_name: ${REDIS_CONTAINER_NAME}

networks:
  backend:
    driver: bridge
